on:
  push:
    branches: [ $default-branch ]
  pull-request:
   branches: [ $default-branch ]
jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:

      - name: step 1
        run:  echo "first step"

      - name: step 2
        run:  echo "second step"
